// <auto-generated />
using EcommercePrototype.API.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommercePrototype.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240127153232_SeedProductData")]
    partial class SeedProductData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcommercePrototype.Core.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Polo tshirts are best to wear at summer. Provides sweatfree days in hot days",
                            Name = "Polo Tshirt",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Formal shirts are all weather shirts that can be used for daily office fashion",
                            Name = "Formal Shirt",
                            Price = 300m
                        },
                        new
                        {
                            Id = 3,
                            Description = "The shoes that you can wear while playing sports, walking, running or jogging",
                            Name = "Sport shoes",
                            Price = 600m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Prmosie your eyes to protect them from dust and dirt",
                            Name = "Eye protecting glasses",
                            Price = 100m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
